#ifndef ONBOARD_LITE_ONBOARD_MODULES_H_
#define ONBOARD_LITE_ONBOARD_MODULES_H_

#ifndef __x86_64__     // it's on arm64
#ifndef CROSS_COMPILE  // CROSS_COMPILE not defined
#include "onboard/camera/image_forwarding_module.h"
#include "onboard/camera/image_publisher_module.h"
#include "onboard/camera/image_sender_module.h"
#include "onboard/can/can_bus_module.h"
#include "onboard/localization/localization_module.h"
#include "onboard/logging/logging_module.h"
#include "onboard/node/node_module.h"
#include "onboard/node/node_state_module.h"
#include "onboard/positioning/drivers/gnss_imu_driver_module.h"
#include "onboard/positioning/positioning_module.h"
#include "onboard/radar/radar_process_module.h"
#include "onboard/radar/radar_publisher_module.h"
#include "onboard/rsim/playback/rsim_playback_module.h"
#include "onboard/rsim/vehicle/rsim_vehicle_module.h"
#include "onboard/vis/qview_publisher_module.h"
#include "onboard/vis/vantage_forwarding_module.h"
#else  // CROSS_COMPILE defined
// NOTE(zhangjie):
// add the modules can work with cross compile
#include "onboard/autonomy_state/autonomy_state_module.h"
#include "onboard/can/can_bus_module.h"
#include "onboard/control/calibration/control_calibration_module.h"
#include "onboard/control/vehicle_control_module.h"
#include "onboard/emergency_brake/emergency_brake_module.h"
#include "onboard/hmi/autonomy_hmi_module.h"
#include "onboard/lidar/spin_publisher_module.h"
#include "onboard/localization/localization_module.h"
#include "onboard/logging/logging_module.h"
#include "onboard/node/node_module.h"
#include "onboard/node/node_state_module.h"
#include "onboard/occ/host/occ_module.h"
#include "onboard/perception/perception_module.h"
#include "onboard/perception/tracker_module.h"
// #include "onboard/perception/vision_module.h"
// #include "onboard/planner/planner_module.h"
// #include "onboard/planner/router/routing_module.h"
// #include "onboard/planner/router/route_recorder_module.h"
#include "onboard/positioning/drivers/gnss_imu_driver_module.h"
#include "onboard/positioning/positioning_module.h"
#include "onboard/radar/radar_process_module.h"
#include "onboard/radar/radar_publisher_module.h"
// #include "onboard/rsim/playback/rsim_playback_module.h"
// #include "onboard/rsim/vehicle/rsim_vehicle_module.h"
// #include "onboard/vis/vantage_forwarding_module.h"
#endif  // done with CROSS_COMPILE
#else   // on x86_64 platform
#include "onboard/autonomy_state/autonomy_state_module.h"
#include "onboard/camera/image_publisher_module.h"
#include "onboard/camera/image_sender_module.h"
#include "onboard/can/can_bus_module.h"
#include "onboard/control/calibration/control_calibration_module.h"
#include "onboard/control/vehicle_control_module.h"
#include "onboard/emergency_brake/emergency_brake_module.h"
#include "onboard/hmi/autonomy_hmi_module.h"
#include "onboard/lidar/spin_publisher_module.h"
#include "onboard/lite/schedule_test_module.h"
#include "onboard/localization/localization_module.h"
#include "onboard/logging/logging_module.h"
#include "onboard/node/node_module.h"
#include "onboard/node/node_state_module.h"
#include "onboard/occ/host/occ_module.h"
#include "onboard/perception/perception_module.h"
#include "onboard/perception/tracker_module.h"
#include "onboard/perception/vision_module.h"
#include "onboard/planner/planner_module.h"
#include "onboard/planner/router/route_recorder_module.h"
#include "onboard/planner/router/routing_module.h"
#include "onboard/positioning/drivers/gnss_imu_driver_module.h"
#include "onboard/positioning/positioning_module.h"
#include "onboard/radar/radar_process_module.h"
#include "onboard/radar/radar_publisher_module.h"
#include "onboard/remote_assist/remote_assist_module.h"
#include "onboard/rsim/playback/rsim_playback_module.h"
#include "onboard/rsim/state_monitor/rsim_state_monitor_module.h"
#include "onboard/rsim/vehicle/rsim_vehicle_module.h"
#include "onboard/sensor_live/sensor_live_module.h"
#include "onboard/simulation/online_simulation_module.h"
#include "onboard/simulation/test_module_state_module.h"
#include "onboard/v2x/v2x_module.h"
#include "onboard/vis/qshow_publisher_module.h"
#include "onboard/vis/qview_publisher_module.h"
#include "onboard/vis/vantage_forwarding_module.h"
#endif  // Done with __x86_64__

#endif  // ONBOARD_LITE_ONBOARD_MODULES_H_
