package(default_visibility = ["//visibility:public"])

filegroup(
    name = "launch_config_files",
    data = glob([
        "*.pb.txt",
    ]),
)

filegroup(
    name = "module_config_files",
    data = glob([
        "module_configs/*.pb.txt",
    ]),
)
